### ISSUE TITLE
Cannot find the file specified

### ISSUE THREAD

**Issue by ZangLucarson** [1m2r3a/AURASync#1]
Whenever I try to run the program in Visual Studio, I get the error "Unable to start program (location)\AuraSyncGDI.exe"
The system cannot find the file specified.

**Comment by 1m2r3a** [comment]
Did you try to rebuild the project before running it?

**Comment by ZangLucarson** [comment]
I tried rebuilding it and when I ran it, the program opened a cmd and closed with no text appearing inside. 
Is this supposed to happen? 
(forgot to mention I'm a little new to visual studio)

**Comment by ZangLucarson** [comment]
I tried debugging and got this error
Exception thrown at 0x0F28A283 (AURA_SDK.dll) in AuraSyncGDI.exe: 0xC0000005: Access violation reading location 0x82A83607. occurred

**Comment by 1m2r3a** [comment]
> I tried rebuilding it and when I ran it, the program opened a cmd and closed with no text appearing inside.

This is happening because you are running in debug mode. Use ctrl+F5 to run the program or Debug>>Run without Debugging.

Do you have read/write rights? You could try running Asus Aura program.

**Comment by ZangLucarson** [comment]
ReachedReachedN
(directory) (process 14952) exited with code -1073741819.
Press any key to close this window . . .

I got this error after trying to do ctrl + f5

**Comment by ZangLucarson** [comment]
And by read and write rights do you mean just the ability to view and create files on my computer?

**Comment by 1m2r3a** [comment]
Do you have AuraSdk installed on your PC? with the Aura service running? Also the AuraSDK.dll should be in the same folder. 

Temporary I am having a problem with AURA software and I cannot start it.

**Comment by ZangLucarson** [comment]
I have it installed and Auraservice.exe is running in the background
So do I just put the AuraSDK.dll in the same folder as the release I compiled?

**Comment by ZangLucarson** [comment]
Ok, I found the problem, something was up with my AuraSDK.dll, but it's all good now!
I ran it and it works fine! Now the only issue is setting it up to work with my weirdly wired RGB haha
